### ISSUE TITLE
How to test rules with @not_implemented arguments?

### ISSUE THREAD

**Issue by st--** [JuliaDiff/ChainRulesTestUtils.jl#217]
If I write a, say, `rrule` that returns NoTangent() for some of the arguments, then `test_rrule` ignores those arguments and everything is fine. However, if I want to be more explicit and make use of `@not_implemented("...")` for some of the arguments, then `test_rrule` fails with
```
test_rrule: newton_inner_loop on Matrix{Float64},typeof(dist_y_given_f),Vector{Bool}: Test Failed at ~/.julia/packages/ChainRulesTestUtils/KlXK9/src/testers.jl:233
  Expression: ad_cotangent isa NoTangent
   Evaluated: NotImplemented(<...>) isa NoTangent
```

How am I supposed to test rules for which I want to make use of `@not_implemented`?
Should https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/a46fbbc1348c4ab1dc455cf5352f972295de967e/src/testers.jl#L233  get wrapped in an if clause that makes the line also pass if ad_cotangent isa NotImplemented ? (Happy to submit a PR including a regression test if that's the way to go.)

**Comment by oxinabox** [comment]
What was the call to `test_rrule` you made?
Did you pass a thing telling `test_rrule` something was `NoTangent` when actually it was `NotImplemented`? Those are distinct things and so it would be correct to fail.

I think it should just work: there is logic in `test_approx` that checks for `NotImplemented`
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/master/src/check_result.jl

But there could well be bugs in it.

A MWE would be useful.

**Comment by devmotion** [comment]
It should just work: https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/a46fbbc1348c4ab1dc455cf5352f972295de967e/test/testers.jl#L642-L647

But maybe I missed something, so a MWE would be good :slightly_smiling_face:

**Comment by devmotion** [comment]
Another example are the tests in SpecialFunctions (the definitions there use `@not_implemented` since some derivatives can't be implemented without a lot of effort and/or introducing additional dependencies) which don't have to handle `@not_implemented` in a special way: https://github.com/JuliaMath/SpecialFunctions.jl/blob/master/test/chainrules.jl

**Comment by st--** [comment]
MRE:
```julia
using ChainRulesCore
using ChainRulesTestUtils

function foo(K, fun)
    return 2K
end

function ChainRulesCore.rrule(::typeof(foo), K, fun)
    f = foo(K, fun)

    function pullback(Δf)
        ∂self = NoTangent()
        ∂K = @thunk(2Δf)
        ∂fun = @not_implemented("does not work")  # does not work
        #∂fun = NoTangent()  # uncommenting this line makes it work

        return (∂self, ∂K, ∂fun)
    end

    return f, pullback
end

test_rrule(foo, 1.1, identity)  # does not work
```

**Comment by mzgubic** [comment]
Oh, it's probably because `rand_tangent` of a function is `NoTangent()`

**Comment by st--** [comment]
It breaks the same for `test_rrule(foo, 1.1, 5)`, and for explicitly passing a tangent:
`test_rrule(foo, 1.1, identity ⊢ NoTangent())`

**Comment by devmotion** [comment]
`rand_tangent` for integers is also `NoTangent()` :wink: 

It works if you specify e.g. `test_rrule(foo, 1.1, identity ⊢ ZeroTangent())`. But probably it's best to just include the case with `NoTangent` in the checks.

**Comment by devmotion** [comment]
Maybe we could handle it by replacing https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/a46fbbc1348c4ab1dc455cf5352f972295de967e/src/testers.jl#L233
with
```julia
                if ad_cotangent isa NotImplemented
                    # https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/217
                    @test_broken ad_cotangent isa NoTangent
                else
                    @test ad_cotangent isa NoTangent  # we said it wasn't differentiable.
                end
```
(with Julia 1.7 one could just use `@test ad_cotangent isa NoTangent broken=(ad_cotangent isa NotImplemented)`)

**Comment by mzgubic** [comment]
I suspect the assertion above will also fail?

**Comment by devmotion** [comment]
No, it doesn't. FD doesn't know about `NotImplemented`.

**Comment by devmotion** [comment]
I'll put together a PR and then we can discuss details and alternatives there :slightly_smiling_face:

**Comment by mzgubic** [comment]
Thanks! My impression was that `fd_cotangent` would just be some number (precisely because it doesn't know about `NotImplemented`)?

**Comment by oxinabox** [comment]
Right I see what is happening.
Since we automatically determine that the tangent for anything without fields (like most functions) is `NoTangent`
and so we take the code path that exist to tell finite differencing to not worry about it, and that then checks that the `rrule` also said it has no fields.

https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/217#issuecomment-923917883
I guess it makes sense to allow people say anything is not implemented.
But in the examples from https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/217#issuecomment-923898645
the implementation is so simple being that it is just `NoTangent()`.

I guess a realistic case maybe needs to handle that those might be closures or functors.
In which case implementing is as:
```julia
∂fun = Base.issingletontype(typeof(fun)) ? NoTangent() : @not_implemented("Functors not supported") 
```
kind of seems better than leaving it as always `@not_implemented`.
I guess they do get informed of that by that `@test_broken`

Ok I started writing this reply as saying this seem bad but I have talked myself round.
Let's do that.
I have assigned to @devmotion.
