### ISSUE TITLE
`_can_pass_early` with `missing`

### ISSUE THREAD

**Issue by theogf** [JuliaDiff/ChainRulesTestUtils.jl#270]
It's me again!

I have an issue on one of my `test_rrule` involving `missing` values.  The `_can_pass_early` test fails to pass as both `actual` and `expected` are equal to `missing`. Naturally `missing == missing` returns `missing` and make the test fails. Using `isequal` solves the issue but I guess that's also not the wanted behaviour.

Any clue on how to solve this?

**Comment by oxinabox** [comment]
When we thought about this before, we were like _"Let's not spend to much time thinking about this, when is a tangent actually going to be `missing`"_
so we didn't think on it too hard.

Can you tell more about why that tangent is `missing`?
It will help us determine what the correct behavour is.

**Comment by theogf** [comment]
So the `Tangent` itself is not `missing`, it is already properly set to `NoTangent` and after more care, I would argue it's more a problem of #271 where `missing` actually comes from `to_vec` with `FiniteDifferences` producing `ismissing`. In the context of `test_approx`, `iszero(missing)` is called and hence the `missing` comparison.

**Comment by oxinabox** [comment]
I see.
Yeah so it was getting `expected` wrong because FiniteDifferences couldn't handle it,
and `actual` was not infact set to `missing`.

Sounds like we should either change it so that that `_can_pass_early` should return false (rather than erroring with `missing` but that's low priority.
I guess it would be an easy check to add as `ismissing(expected)` but also if you are ended up with `expected===missing` probably something else is wrong anyway and so the error is kinda more useful?

So maybe we can close this?
